export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  LOGIN: '/login',
  LANDING: '/landing',
  REGISTER:'/register',
  FORGET_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:email',
  PASSWORD_CHANGED: '/password-changed',
  PRIVACY_NOTICE: '/privacy-policy',
  TERMS_OF_USE: '/terms-of-use',
  VERIFY_ACCOUNT:'/verify-account/:email',
  LISTING: '/listing',
  UPDATE_LISTING: '/listing/edit',
  CREATE_LISTING: '/listing/create',
  BOOK_LISTING: '/listing/book',
  GUEST: '/guest',
  ROOM: '/room',
  BOOKING: '/booking',
  REPORT: '/report',
  SETTING: '/setting',
}